package document_schema

const (
	AdditionalPropertiesSchemaKeyword = "additionalProperties"
	AllOfSchemaKeyword                = "allOf"
	AnyOfSchemaKeyword                = "anyOf"
	DefaultSchemaKeyword              = "default"
	DependenciesSchemaKeyword         = "dependencies"
	DeprecatedSchemaKeyword           = "deprecated"
	DiscriminatorSchemaKeyword        = "discriminator"
	EnumSchemaKeyword                 = "enum"
	FormatSchemaKeyword               = "format"
	ItemsSchemaKeyword                = "items"
	MaximumSchemaKeyword              = "maximum"
	ExampleSchemaKeyword              = "example"
	ExclusiveMaximumSchemaKeyword     = "exclusiveMaximum"
	MaxItemsSchemaKeyword             = "maxItems"
	MaxLengthSchemaKeyword            = "maxLength"
	MaxPropertiesSchemaKeyword        = "maxProperties"
	MappingSchemaKeyword              = "mapping"
	MinimumSchemaKeyword              = "minimum"
	ExclusiveMinimumSchemaKeyword     = "exclusiveMinimum"
	MinItemsSchemaKeyword             = "minItems"
	MinLengthSchemaKeyword            = "minLength"
	MinPropertiesSchemaKeyword        = "minProperties"
	MultipleOfSchemaKeyword           = "multipleOf"
	NotSchemaKeyword                  = "not"
	NullableSchemaKeyword             = "nullable"
	OneOfSchemaKeyword                = "oneOf"
	PatternSchemaKeyword              = "pattern"
	PropertiesSchemaKeyword           = "properties"
	RefSchemaKeyword                  = "$ref"
	RequiredSchemaKeyword             = "required"
	TypeSchemaKeyword                 = "type"
	UniqueItemsSchemaKeyword          = "uniqueItems"
	TitleSchemaKeyword                = "title"
	DescriptionSchemaKeyword          = "description"
	ReadOnlySchemaKeyword             = "readOnly"
	WriteOnlySchemaKeyword            = "writeOnly"

	TypeArraySchemaKeyword   = "array"
	TypeBooleanSchemaKeyword = "boolean"
	TypeIntegerSchemaKeyword = "integer"
	TypeNumberSchemaKeyword  = "number"
	TypeObjectSchemaKeyword  = "object"
	TypeStringSchemaKeyword  = "string"

	FormatInt32SchemaKeyword        = "int32"
	FormatInt64SchemaKeyword        = "int64"
	FormatFloatSchemaKeyword        = "float"
	FormatDoubleSchemaKeyword       = "double"
	FormatBinarySchemaKeyword       = "binary"
	FormatByteSchemaKeyword         = "byte"
	FormatPasswordSchemaKeyword     = "password"
	FormatDateSchemaKeyword         = "date"
	FormatDateTimeSchemaKeyword     = "date-time"
	FormatEmailSchemaKeyword        = "email"
	FormatHostnameSchemaKeyword     = "hostname"
	FormatIpV4SchemaKeyword         = "ipv4"
	FormatIpV6SchemaKeyword         = "ipv6"
	FormatURISchemaKeyword          = "uri"
	FormatURIREFSchemaKeyword       = "uriref"
	FormatURIReferenceSchemaKeyword = "uri-reference"
	FormatUUIDSchemaKeyword         = "uuid"
)
